AWSTemplateFormatVersion: '2010-09-09'

Description: Creates S3 bucket and DynamoDB backends for Terraform remote storage and grant admin access policy

Parameters:
  BucketName:
    Type: String
    Description: Used for bucket name - Ex. relus-terraform
    Default: terraform-backend-bucket-0002-1
  TableName:
    Type: String
    Description: Used for dynamodb table name - Ex. relus-terraform
    Default: terraform-backend-table-0002-1
Mappings:
  RegionAMIs:
    us-east-1:
      Name: ami-b70554c8

Resources:
  TerraformAutomationRole:
    Type: AWS::IAM::Role
    Properties:
         AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: Allow
                Principal:
                  Service:
                      - "s3.amazonaws.com"
                      - "ec2.amazonaws.com"
                Action:
                        - "sts:AssumeRole"
         Path: "/"
         ManagedPolicyArns:
            - 'arn:aws:iam::aws:policy/AdministratorAccess'

  InstanceProfile:
      Type: AWS::IAM::InstanceProfile
      Properties:
        Path: "/"
        Roles:
          - Ref: TerraformAutomationRole
      DependsOn: TerraformAutomationRole

  TerraformRemoteStateBucket:
    Type: AWS::S3::Bucket
    DependsOn: TerraformAutomationRole
    Properties:
      BucketName:
        Ref: BucketName
      AccessControl:  LogDeliveryWrite
      VersioningConfiguration:
        Status: Enabled
      Tags:
          -
            Key: "Name"
            Value: "S3Bucket"

  TerraformRemoteStateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: LockID
        AttributeType: S
      KeySchema:
      - AttributeName: LockID
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
      TableName:
        Ref: TableName

Outputs:
  TerraformRemoteStateBucket:
    Value:
      Ref: TerraformRemoteStateBucket
  TerraformRemoteStateTable:
    Value:
      Ref: TerraformRemoteStateTable
